version: "3.7"
services:
  summarization:
    image: legist/summarization:latest
    command: --enable-microbatch --workers=1 --timeout=180
  ner:
    image: legist/ner:latest
    command: --enable-microbatch --workers=1 --timeout=180
  categorization:
    image: legist/categorization:latest
    command: --enable-microbatch --workers=1 --timeout=180
  revproxy:
    image: legist/revproxy:latest
    command: --enable-microbatch --workers=1 --timeout=180
    build:
      context: revproxy
      dockerfile: 'Dockerfile'
    ports:
      - "8000:8000"